### ISSUE TITLE
[Receive] Better UI for ReceiveView

### ISSUE THREAD

**Issue by andrerfneves** [ZcashJS/zcash-electron#4]
## Tasks
- [ ] Implement better UI for form in Receive view

## Acceptance Criteria
This view needs to show:
- [ ] Ability to select an address
- [ ] Ability to see that address' string code
- [ ] Ability to see that address' QR code

## Screenshots
<img width="1357" alt="screen shot 2018-08-18 at 9 26 28 pm" src="https://user-images.githubusercontent.com/2574011/44304575-a7456980-a32d-11e8-968a-9e788f466ba8.png">
